
version: "3"
services:

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
  
  redis:
    image: redis/redis-stack
    volumes:
      - redis_data:/data:rw
    ports:
      - 6379:6379
    restart: unless-stopped

volumes:
  redis_data: