REGISTRY=dogfrogfog
VERSION=dev-admin

install: ## Install the web dependencies
	yarn install --ignore-engines

run-local: ## Run the local dev server
	yarn dev

build-local: ## Build dev version
	yarn build:dev

build-dist: ## Build dist version
	yarn build:dist
