// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: nft/nft.proto

package art_admin

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NftClient is the client API for Nft service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NftClient interface {
	UpsertNFTMintRequest(ctx context.Context, in *NFTMintRequestToUpload, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error)
	ListNFTMintRequests(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NFTMintRequestListArray, error)
	DeleteNFTMintRequestById(ctx context.Context, in *DeleteId, opts ...grpc.CallOption) (*DeleteStatus, error)
	UpdateNFTOffchainUrl(ctx context.Context, in *UpdateNFTOffchainUrlRequest, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error)
	DeleteNFOffchainUrl(ctx context.Context, in *DeleteId, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error)
	UploadOffchainMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MetadataOffchainUrl, error)
	// TODO: add rpc for getting metadata offchain url
	UploadIPFSMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type nftClient struct {
	cc grpc.ClientConnInterface
}

func NewNftClient(cc grpc.ClientConnInterface) NftClient {
	return &nftClient{cc}
}

func (c *nftClient) UpsertNFTMintRequest(ctx context.Context, in *NFTMintRequestToUpload, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error) {
	out := new(NFTMintRequestWithStatus)
	err := c.cc.Invoke(ctx, "/nft.Nft/UpsertNFTMintRequest", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) ListNFTMintRequests(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NFTMintRequestListArray, error) {
	out := new(NFTMintRequestListArray)
	err := c.cc.Invoke(ctx, "/nft.Nft/ListNFTMintRequests", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) DeleteNFTMintRequestById(ctx context.Context, in *DeleteId, opts ...grpc.CallOption) (*DeleteStatus, error) {
	out := new(DeleteStatus)
	err := c.cc.Invoke(ctx, "/nft.Nft/DeleteNFTMintRequestById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) UpdateNFTOffchainUrl(ctx context.Context, in *UpdateNFTOffchainUrlRequest, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error) {
	out := new(NFTMintRequestWithStatus)
	err := c.cc.Invoke(ctx, "/nft.Nft/UpdateNFTOffchainUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) DeleteNFOffchainUrl(ctx context.Context, in *DeleteId, opts ...grpc.CallOption) (*NFTMintRequestWithStatus, error) {
	out := new(NFTMintRequestWithStatus)
	err := c.cc.Invoke(ctx, "/nft.Nft/DeleteNFOffchainUrl", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) UploadOffchainMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*MetadataOffchainUrl, error) {
	out := new(MetadataOffchainUrl)
	err := c.cc.Invoke(ctx, "/nft.Nft/UploadOffchainMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nftClient) UploadIPFSMetadata(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/nft.Nft/UploadIPFSMetadata", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NftServer is the server API for Nft service.
// All implementations should embed UnimplementedNftServer
// for forward compatibility
type NftServer interface {
	UpsertNFTMintRequest(context.Context, *NFTMintRequestToUpload) (*NFTMintRequestWithStatus, error)
	ListNFTMintRequests(context.Context, *emptypb.Empty) (*NFTMintRequestListArray, error)
	DeleteNFTMintRequestById(context.Context, *DeleteId) (*DeleteStatus, error)
	UpdateNFTOffchainUrl(context.Context, *UpdateNFTOffchainUrlRequest) (*NFTMintRequestWithStatus, error)
	DeleteNFOffchainUrl(context.Context, *DeleteId) (*NFTMintRequestWithStatus, error)
	UploadOffchainMetadata(context.Context, *emptypb.Empty) (*MetadataOffchainUrl, error)
	// TODO: add rpc for getting metadata offchain url
	UploadIPFSMetadata(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
}

// UnimplementedNftServer should be embedded to have forward compatible implementations.
type UnimplementedNftServer struct {
}

func (UnimplementedNftServer) UpsertNFTMintRequest(context.Context, *NFTMintRequestToUpload) (*NFTMintRequestWithStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertNFTMintRequest not implemented")
}
func (UnimplementedNftServer) ListNFTMintRequests(context.Context, *emptypb.Empty) (*NFTMintRequestListArray, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNFTMintRequests not implemented")
}
func (UnimplementedNftServer) DeleteNFTMintRequestById(context.Context, *DeleteId) (*DeleteStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNFTMintRequestById not implemented")
}
func (UnimplementedNftServer) UpdateNFTOffchainUrl(context.Context, *UpdateNFTOffchainUrlRequest) (*NFTMintRequestWithStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNFTOffchainUrl not implemented")
}
func (UnimplementedNftServer) DeleteNFOffchainUrl(context.Context, *DeleteId) (*NFTMintRequestWithStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNFOffchainUrl not implemented")
}
func (UnimplementedNftServer) UploadOffchainMetadata(context.Context, *emptypb.Empty) (*MetadataOffchainUrl, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadOffchainMetadata not implemented")
}
func (UnimplementedNftServer) UploadIPFSMetadata(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadIPFSMetadata not implemented")
}

// UnsafeNftServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NftServer will
// result in compilation errors.
type UnsafeNftServer interface {
	mustEmbedUnimplementedNftServer()
}

func RegisterNftServer(s grpc.ServiceRegistrar, srv NftServer) {
	s.RegisterService(&Nft_ServiceDesc, srv)
}

func _Nft_UpsertNFTMintRequest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NFTMintRequestToUpload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).UpsertNFTMintRequest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/UpsertNFTMintRequest",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).UpsertNFTMintRequest(ctx, req.(*NFTMintRequestToUpload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_ListNFTMintRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).ListNFTMintRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/ListNFTMintRequests",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).ListNFTMintRequests(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_DeleteNFTMintRequestById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).DeleteNFTMintRequestById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/DeleteNFTMintRequestById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).DeleteNFTMintRequestById(ctx, req.(*DeleteId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_UpdateNFTOffchainUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNFTOffchainUrlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).UpdateNFTOffchainUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/UpdateNFTOffchainUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).UpdateNFTOffchainUrl(ctx, req.(*UpdateNFTOffchainUrlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_DeleteNFOffchainUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).DeleteNFOffchainUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/DeleteNFOffchainUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).DeleteNFOffchainUrl(ctx, req.(*DeleteId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_UploadOffchainMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).UploadOffchainMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/UploadOffchainMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).UploadOffchainMetadata(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Nft_UploadIPFSMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NftServer).UploadIPFSMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nft.Nft/UploadIPFSMetadata",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NftServer).UploadIPFSMetadata(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Nft_ServiceDesc is the grpc.ServiceDesc for Nft service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Nft_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nft.Nft",
	HandlerType: (*NftServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertNFTMintRequest",
			Handler:    _Nft_UpsertNFTMintRequest_Handler,
		},
		{
			MethodName: "ListNFTMintRequests",
			Handler:    _Nft_ListNFTMintRequests_Handler,
		},
		{
			MethodName: "DeleteNFTMintRequestById",
			Handler:    _Nft_DeleteNFTMintRequestById_Handler,
		},
		{
			MethodName: "UpdateNFTOffchainUrl",
			Handler:    _Nft_UpdateNFTOffchainUrl_Handler,
		},
		{
			MethodName: "DeleteNFOffchainUrl",
			Handler:    _Nft_DeleteNFOffchainUrl_Handler,
		},
		{
			MethodName: "UploadOffchainMetadata",
			Handler:    _Nft_UploadOffchainMetadata_Handler,
		},
		{
			MethodName: "UploadIPFSMetadata",
			Handler:    _Nft_UploadIPFSMetadata_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nft/nft.proto",
}
