name: Check test coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run tests and check coverage
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true

      - name: Set up buf 
        uses: bufbuild/buf-setup-action@v1.6.0

      - name: Install and test 
        run: |
          make install && 
          export PATH="$PATH:$(go env GOPATH)/bin" 
          make test
          
    

    