name: Check test coverage

on:
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Push Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'
          check-latest: true

      - name: Install dependencies 
        run: |
          make install

      - name: Run tests
        run: |
          make test
    

    